import type { Config } from "drizzle-kit";

export default {
  schema: "./lib/db/schema/index.ts",
  out: "./supabase/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env["DATABASE_URL"]!,
  },
  // Include views generated by Supabase (auth.users, etc.)
  extensionsFilters: ["postgis"],
  schemaFilter: ["public"],
  verbose: true,
  strict: true,
} satisfies Config;
